// SPDX-License-Identifier: MIT
// AUTO-GENERATED by coordinator/gen_fixture.py — do not edit by hand.
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {ThicketToken} from "../src/ThicketToken.sol";
import {RewardsDistributor, IThicketToken} from "../src/RewardsDistributor.sol";

/// Proves the Python Merkle tree (coordinator) and Solidity claim verifier agree.
contract MerkleInteropTest is Test {
    ThicketToken token;
    RewardsDistributor dist;
    address owner = address(0xA11CE);

    function setUp() public {
        vm.startPrank(owner);
        token = new ThicketToken(0, 100_000_000e18, owner);
        dist = new RewardsDistributor(IThicketToken(address(token)), owner);
        token.setMinter(address(dist));
        dist.setPublisher(owner);
        dist.publishRoot(0xa006d4749e58fd19fa57edf41a73e5248e44cec52ea49326647762b45ddc7f16);
        vm.stopPrank();
    }

    function test_pythonProofVerifiesOnChain() public {
        bytes32[] memory proof = new bytes32[](2);
        proof[0] = 0xe8e283b357d511900081a8c9c8cfbb5af5a73448217a85dc7515e5262cf0ac7b;
        proof[1] = 0x8b35091f8eba30468af830c793c10a5601a0fcc772d63394e1a69faa1c8aeb24;
        dist.claim(0x0000000000000000000000000000000000000B0b, 1000000000000000000, proof);
        assertEq(token.balanceOf(0x0000000000000000000000000000000000000B0b), 1000000000000000000);
    }
}
