"""
Generate a Merkle fixture and emit a Solidity test that consumes it, proving
the Python tree and the on-chain RewardsDistributor agree on leaf/root/proof
encoding. Run after changing merkle.py:

    python gen_fixture.py   # writes ../contracts/test/MerkleInterop.t.sol
"""
from __future__ import annotations

from app.merkle import MerkleTree

# Deterministic sample: (address, cumulativeAmount) leaves.
ENTRIES = [
    ("0x000000000000000000000000000000000000dEaD", 42 * 10**18),
    ("0x00000000000000000000000000000000DeaDBeef", 7 * 10**18),
    ("0x0000000000000000000000000000000000000B0b", 1 * 10**18),
]

tree = MerkleTree(ENTRIES)
claims = tree.claims()
# Pick the account that is NOT last in the sorted tree so the proof is non-empty.
target = tree.entries[0][0]
amount = tree.entries[0][1]
proof = claims[target]["proof"]

proof_lits = "".join(f"        proof[{i}] = {p};\n" for i, p in enumerate(proof))

sol = f"""// SPDX-License-Identifier: MIT
// AUTO-GENERATED by coordinator/gen_fixture.py — do not edit by hand.
pragma solidity ^0.8.24;

import {{Test}} from "forge-std/Test.sol";
import {{ThicketToken}} from "../src/ThicketToken.sol";
import {{RewardsDistributor, IThicketToken}} from "../src/RewardsDistributor.sol";

/// Proves the Python Merkle tree (coordinator) and Solidity claim verifier agree.
contract MerkleInteropTest is Test {{
    ThicketToken token;
    RewardsDistributor dist;
    address owner = address(0xA11CE);

    function setUp() public {{
        vm.startPrank(owner);
        token = new ThicketToken(0, 100_000_000e18, owner);
        dist = new RewardsDistributor(IThicketToken(address(token)), owner);
        token.setMinter(address(dist));
        dist.setPublisher(owner);
        dist.publishRoot({tree.root_hex()});
        vm.stopPrank();
    }}

    function test_pythonProofVerifiesOnChain() public {{
        bytes32[] memory proof = new bytes32[]({len(proof)});
{proof_lits}        dist.claim({target}, {amount}, proof);
        assertEq(token.balanceOf({target}), {amount});
    }}
}}
"""

out = "../contracts/test/MerkleInterop.t.sol"
with open(out, "w") as f:
    f.write(sol)
print(f"root: {tree.root_hex()}")
print(f"wrote {out} (claim for {target}, proof len {len(proof)})")
